apiVersion: v1
kind: ConfigMap
metadata:
  name: home-hub-config
  namespace: home-hub
data:
  NODE_ENV: "development"
  PORT: "5000"
  # Add your home IP addresses here
  ALLOWED_IPS: "127.0.0.1,::1,YOUR_HOME_IP_HERE"